---
user: oleenger
home_folder: "/home/{{ user }}"

version: "0.9.4"
appimage_url: "https://github.com/neovim/neovim/releases/download/v{{ version }}/nvim.appimage"
dl_dir: "/opt/nvim/{{ version }}"
config_folder: "{{ home_folder }}/.config/nvim"
config_repo: https://github.com/oleenger/nvim.git
