---
- name: Cleanup
  ansible.builtin.import_tasks: cleanup.yml
  tags: cleanup

- name: Install Neovim
  ansible.builtin.import_tasks: install.yml
  tags: install

- name: Install Packer
  ansible.builtin.import_tasks: packer.yml
  tags: packer
