---
- name: Clean config
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ home_folder }}/.config"

- name: Config repo
  ansible.builtin.git:
    repo: "{{ config.repo }}"
    dest: "{{ config.folder }}"
